name = "GraphCore"
uuid = "959eb29d-3b89-4f5f-bee6-61f8037ea4e1"
authors = ["Jack Lidmar <jlidmar@kth.se>"]
version = "0.5.1"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "^1.3"
GraphRecipes = "^0.5"
Graphs = "^1.13"
Plots = "^1.38"
SimpleWeightedGraphs = "^1.5"
StaticArrays = "^1.9"
julia = "^1.11"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
benchmarks = ["BenchmarkTools"]
plotting = ["Plots", "GraphRecipes"]
test = ["Test"]
